# Generated by Django 3.0 on 2020-01-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_depart', models.CharField(max_length=50)),
                ('station_arrive', models.CharField(max_length=50)),
                ('num_adult', models.CharField(max_length=50)),
                ('num_child', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('time_begin', models.CharField(max_length=50)),
                ('time_end', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
