# Generated by Django 2.2.9 on 2020-01-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200115_0627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
