# Generated by Django 2.2.9 on 2020-01-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='lambda_status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
